---
title: "Analytics Portfolio"
---

**Lauren Cardieri** 

--- 


# Education: 
- MS in Business Analytics, *CUNY Baruch*
- BS in Mathematics with Concentration in Education 7-12, *CUNY College of Staten Island*

---

# Projects:

- **Personality Test: Introvert vs Extrovert**
     - Click [here](https://personalitytest.streamlit.app/) to view
     
- **A.I. Mood-Based Game Recommender**
     - Click [here](https://mood-based-game-rec.streamlit.app/) to view
     
- **Healthcare Charge Predictor**
     - Click [here](https://insurance-charge.streamlit.app/) to view
     

- **Fiscal Characteristics of Major US Public Transit Systems**
     - Click [here](https://laurencardieri.github.io/STA9750-2024-FALL/mp01.html) to view
     
     
- **The Business of Show Business**
     - Click [here](https://laurencardieri.github.io/STA9750-2024-FALL/mp02.html) to view
     
     
- **Do Proportional Electoral College Allocations Yield a More Representative Presidency?**
     - Click [here](https://laurencardieri.github.io/STA9750-2024-FALL/mp03.html) to view

 - **Monte Carlo-Informed Selection of CUNY Retirement Plans**
     - Click [here](https://laurencardieri.github.io/STA9750-2024-FALL/mp04.html) to view
     
- **Broker T’s: Mortgages: What’s the Big Deal? (Individual)**
     - Click [here](https://laurencardieri.github.io/STA9750-2024-FALL/Final_Individual.html#data-sources) to view
     

--- 

Github Username: laurencardieri