<div style="text-align: center;">
# Mini-Project #04: Monte Carlo-Informed Selection of CUNY Retirement Plans
</div>

# Introduction


Newly hired at CUNy, I have thirty days to choose between one of two retirement plans. These two plans can be viewed [here](https://www.cuny.edu/wp-content/uploads/sites/4/page-assets/about/administration/offices/hr/benefits/Benefits-Guide-Retirement-Plans-Final-HEO-and-ECP.pdf). This is an early choice for faculty and is important as it is essentially permanent and cannot be changed. In this project, I will use historical financial data and a bootstrap inference strategy to estimate the probability that one plan is better than the other. 

The two plans are better explained below: 

## Teachers Retirement System (TRS)

The TRS plan is a traditional pension plan: after retirement, the employer continues to pay employees a fraction of their salary until death. This type of plan is called a “defined-benefit” because the retirement pay is fixed a priori and the employer takes the market risk. If the market under performs expectations, CUNY has to make up the gap; if the market over performs expectations, CUNY pockets the excess balance.

Employees pay a fixed percentage of their paycheck into the pension fund. The contribution rates are based on employee's salary amount, and are as follows: 

- $45,000 or less: 3%
- $45,001 to $55,000: 3.5%
- $55,001 to $75,000: 4.5%
- $75,001 to $100,000: 5.75%
- $100,001 or more: 6%

Then, the retirement benefit is calculated based on the *Final three years salary* of the employee, which changed after 2024. Before 2024, it was based on the prior five years. 

If **N** is the number of years served, the annual retirement benefit is: 

- 1.67% * FAS * N, if N is less than 20 years
- 1.75% * FAS * N, if N is equal to 20 years
- (35% + 2% * N) * FAS, if N is greater than 20 years

In each case, the benefit is paid out equally over 12 months. 

The benefit is increased annually by 50% of the CPI, rounded up to the nearest tenth of a percent. For example, a CPI of 2.9% gives an inflation adjustment of 1.5%. The benefit is capped below at 1% and above at 3%, so a CPI of 10% leads to a 3% inflation adjustment while a CPI of 0% leads to a 1% inflation adjustment.

The inflation adjustment is effective each September and the CPI used is the aggregate monthly CPI of the previous 12 months; so the September 2024 adjustment depends on the CPI from September 2023 to August 2024.


## Optional Retirement Plan (ORP)

The ORP plan is more similar to a 401(k) plan offered by a private employer. The employee and the employer both make contributions to a retirement account which is then invested in the employee’s choice of mutual funds. Those investments grow “tax-free” until the employee begins to withdraw them upon retirement. If the employee does not use up the funds, they are passed down to that employee’s spouse, children, or other heirs; if the employee uses the funds too quickly and zeros out the account balance, no additional retirement funds are available. This type of plan is called a defined-contribution plan as only the contributions to the retirement account are fixed by contract: the final balance depends on market factors outside of the employee’s control.


When retired, an employee has access to the funds and can withdraw at any rate they wish. Usually, withdrawing 4% of the value per year is the best practice, but funds in the plan will continue to experience market returns. 

The funds available in an ORP account depend strongly on the investments chosen. For this project, we will assume that participants invest in a Fidelity Freedom Fund with the following asset allocation: 

- Age 25 to Age 49:
     - 54% US Equities
     - 36% International Equities
     - 10% Bonds
     
- Age 50 to Age 59:
     - 47% US Equities
     - 32% International Equities
     - 21% Bonds
- Age 60 to Age 74:
     - 34% US Equities
     - 23% International Equities
     - 43% Bonds
- Age 75 or older: 
     - 19% US Equities
     - 13% International Equities
     - 62% Bonds
     - 6% Short-Term Debt

Both the employee and the employer make monthly contributions to the employee’s ORP account. These returns are calculated as a percentage of the employee’s annual salary, which is the same rate as the TRS:

- $45,000 or less: 3%
- $45,001 to $55,000: 3.5%
- $55,001 to $75,000: 4.5%
- $75,001 to $100,000: 5.75%
- $100,001 or more: 6%

The employer contribution is fixed at:
- 8% for the first seven years of employment at CUNY
- 10% for all years after 


# Data Sources 

For this project, we will use data from two economic and financial data services. They are as follows: 

- [AlphaVantage](https://www.alphavantage.co/): a commercial stock market data provider
- [FRED](https://fred.stlouisfed.org/): the Federal Reserve Economic Data repository maintained by the Federal Reserve Bank of St. Louis

To begin my Monte Carlo analysis, I will need historical data covering the following. For ease, linked the data I plan to use to each point. 

- [Wage Growth](https://fred.stlouisfed.org/series/SMU36935610500000003)
- [Inflation](https://fred.stlouisfed.org/series/CUURA101SA0)
- [US Equity Market Total Returns](https://fred.stlouisfed.org/series/SP500)
- [International Equity Market total returns](https://fred.stlouisfed.org/series/BAMLEMCBPITRIV)
- Bond Market Total Returns
- [Short-term debt returns](https://fred.stlouisfed.org/series/BOGZ1FL634022405Q) 


<details>
  <summary>**Click here to see how the data was downloaded into R**</summary>
```{r}
library(readr)
Estimated_mean_wages <- read_csv("mp4/Estimated_mean_wages.csv")
View(Estimated_mean_wages)


Hourly_Wages <- read_csv("mp4/Hourly_Wages.csv")
View(Hourly_Wages)
                
ICE_BofA_US_High_Yield_Index_Total_Return_Index_Value <- read_csv("mp4/ICE BofA US High Yield Index Total Return Index Value.csv")
View(ICE_BofA_US_High_Yield_Index_Total_Return_Index_Value)

money_market <- read_csv("mp4/money_market.csv")
View(money_market)

nyc_inflation <- read_csv("mp4/nyc_inflation.csv")
View(nyc_inflation)

SP500 <- read_csv("mp4/SP500.csv")
View(SP500)

```
</details>









